<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Joshua Bruno">

<title>The Generational Divide</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Website Ed. The Generational Divide_files/libs/clipboard/clipboard.min.js"></script>
<script src="Website Ed. The Generational Divide_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Website Ed. The Generational Divide_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Website Ed. The Generational Divide_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Website Ed. The Generational Divide_files/libs/quarto-html/popper.min.js"></script>
<script src="Website Ed. The Generational Divide_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Website Ed. The Generational Divide_files/libs/quarto-html/anchor.min.js"></script>
<link href="Website Ed. The Generational Divide_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Website Ed. The Generational Divide_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Website Ed. The Generational Divide_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Website Ed. The Generational Divide_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Website Ed. The Generational Divide_files/libs/bootstrap/bootstrap-a74871fe4945b66d259aafc266475145.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="Website Ed. The Generational Divide_files/libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="Website Ed. The Generational Divide_files/libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question"><span class="header-section-number">2</span> Research Question</a></li>
  <li><a href="#hypothesis" id="toc-hypothesis" class="nav-link" data-scroll-target="#hypothesis"><span class="header-section-number">3</span> Hypothesis</a></li>
  <li><a href="#literature-review" id="toc-literature-review" class="nav-link" data-scroll-target="#literature-review"><span class="header-section-number">4</span> Literature Review</a></li>
  <li><a href="#data-and-descriptive-statistics" id="toc-data-and-descriptive-statistics" class="nav-link" data-scroll-target="#data-and-descriptive-statistics"><span class="header-section-number">5</span> Data and Descriptive Statistics</a></li>
  <li><a href="#model-fitting-and-hypothesis-testing" id="toc-model-fitting-and-hypothesis-testing" class="nav-link" data-scroll-target="#model-fitting-and-hypothesis-testing"><span class="header-section-number">6</span> Model Fitting and Hypothesis Testing</a></li>
  <li><a href="#diagnostics-and-model-evaluation" id="toc-diagnostics-and-model-evaluation" class="nav-link" data-scroll-target="#diagnostics-and-model-evaluation"><span class="header-section-number">7</span> Diagnostics and Model Evaluation</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">8</span> Discussion</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">9</span> Limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">10</span> Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">11</span> References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The Generational Divide</h1>
<p class="subtitle lead">Age and Perceptions of U.S. Political Direction in Europe</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Joshua Bruno </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>This research paper examines how age is associated with European perceptions of the political direction of the United States. Using data from the Standard Eurobarometer 101.3 survey, conducted in spring 2024 across European Union member states, the analysis investigates whether younger and older Europeans differ in their assessment of whether the United States is moving in the “right” or “wrong” direction.</p>
<p>Public opinion toward the U.S. has become an increasingly important topic in Europe in recent years due to geopolitical developments, changes in U.S. leadership, and often-tense transatlantic relations resulting from a nonalignment in policy on major issues. Survey data suggest that overall favorability toward the U.S. has declined in several European countries, with significant variation across demographic groups. This study focuses specifically on age as a potential predictor of these attitudes, while accounting for individual political ideology, social class, and gender.</p>
<p>The analysis uses individual-level survey responses from more than 36,000 respondents across EU member states. The dependent variable is a binary indicator capturing whether respondents believe the United States is moving in the right direction or in the wrong direction. Age is treated as a continuous independent variable, and the model includes controls for political ideology, social class, and gender to isolate the relationship between age and U.S. political perceptions.</p>
<p>By identifying whether age is systematically related to evaluations of U.S. political direction, this paper contributes evidence to discussions about generational differences in international political attitudes within Europe. The findings provide a descriptive and statistical assessment of how opinions about the U.S. vary across age cohorts at a time of heightened geopolitical tension so close to the present day.</p>
</section>
<section id="research-question" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="research-question"><span class="header-section-number">2</span> Research Question</h2>
<p><strong>The research question is as follows:</strong> To what extent is age associated with Europeans’ assessments of whether the United States is moving in the “right” or “wrong” direction?</p>
<p>This research question carries important historical implications for the future of transatlantic relations. For much of the post–World War II period, the United States has been widely regarded as a beacon of liberal democracy and it’s President commonly described as the “leader of the free world.” This reputation has played a major role in shaping European perceptions of American political legitimacy and leadership. However, recent political developments and perceived departures from these values have raised questions about whether this image remains intact, particularly among younger Europeans. If young people increasingly view the U.S. less favorably, this may signal a generational shift in how American leadership is understood and evaluated. As political influence gradually transitions from older generations to younger ones within European societies, such changes in perception could have long-term consequences for diplomatic cooperation, alliance formation, and the foundations of the transatlantic relationship.</p>
<p>This research question is especially important to examine at the present moment because public perceptions of the U.S. appear to be shifting (really worsening) in real time. The use of recent, large-scale survey data allows for an assessment of these dynamics at a critical juncture. The Eurobarometer 101.3 survey, fielded in spring 2024, captures European attitudes toward the U.S. in the aftermath of significant political and geopolitical developments that have elicited strong public reactions, most notably the United States’ support for Israel in its aggression in the Palestinian Territories following the October 7, 2023 attack by Hamas, and America’s hesitancy to fully commit to defending Ukraine in its war against the Russian Federation. Analyzing data collected during this period provides a rare opportunity to observe age-based differences as they emerge, rather than relying on retrospective accounts. While the analysis cannot predict future outcomes directly, identifying generational patterns in contemporary data helps inform expectations about how European perceptions of the U.S. may evolve as demographic change continues.</p>
</section>
<section id="hypothesis" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="hypothesis"><span class="header-section-number">3</span> Hypothesis</h2>
<p>Political socialization theory argues that individuals form lasting orientations toward international actors and institutions based on the political events present during their formative years (Jennings, Stoker, &amp; Bowers 2009, pp.&nbsp;782; 793–794). On the one hand, older Europeans brought up during the Cold War or the era of post-9/11 transatlantic solidarity may maintain more favorable views of the United States due to long-standing narratives highlighting security cooperation and democratic partnership and values. On the other hand, younger Europeans have grown up in a different geopolitical environment characterized by two-party polarization within the U.S., controversial foreign policy, and a broader heightened global scrutiny of American leadership.</p>
<p>Consistent with this shift, the Pew Research Center (2023) finds that young adults in major European democracies exhibit significantly lower levels of trust and favorability toward the U.S. than older generations. Combined with evidence from the YouGov EuroTrack survey, which documents historically low U.S. favorability across Europe following the 2024 U.S. Presidential election, these trends suggest a generational realignment in transatlantic attitudes. Younger Europeans appear increasingly skeptical of U.S. political direction, while older Europeans maintain more positive views by comparison.</p>
<p><strong>Hypothesis:</strong> Younger European citizens will be less likely to perceive the United States as moving in the “Right Direction” compared to older citizens, controlling for political ideology and social class.</p>
</section>
<section id="literature-review" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="literature-review"><span class="header-section-number">4</span> Literature Review</h2>
<p>A longstanding debate in political science concerns how states acquire and sustain influence in the international system. Beyond military and economic strength, scholars have emphasized the role of attraction, legitimacy, and shared values in shaping overall national might. Nye’s (1990) concept of “soft power” argues that cultural influence, political ideals, and perceived moral authority can generate support for a country’s global leadership without coercion. For much of the post-World War II period, the United States benefited disproportionately from these dynamics, particularly in Western Europe, where American ideals, cultural exchange, and institutional cooperation reinforced favorable public perceptions.</p>
<p>Scholarly work that came later expanded on this framework by highlighting the importance of public opinion in sustaining international influence. Research on transatlantic relations shows that European attitudes toward the United States are closely tied to evaluations of American foreign policy, democratic credibility, and global leadership (Holsti, 2008; Chiozza, 2009). Periods of perceived U.S. unilateralism or value divergence, such as during the Vietnam War or the Iraq War, have historically coincided with drops in European favorability, suggesting that support for U.S. leadership is contingent rather than remaining static.</p>
<p>Political socialization theory provides a useful lens through which we can begin to understand how these dynamics may differ across generations. It posits that attitudes formed during adolescence and early adulthood tend to persist over time, shaping political orientations later in life (Jennings &amp; Niemi, 1981; Jennings et al., 2009). As a result, younger cohorts exposed to different international contexts may develop systematically different views of global actors. In the context of transatlantic relations, this implies that age-based differences in perceptions of the United States may reflect more than a mere temporary dissatisfaction, and instead signal long-term generational divides.</p>
<p>Recent survey evidence points to growing skepticism toward the United States across Western Europe, particularly among younger respondents. Pew Research Center (2023) finds that young adults in the United Kingdom, France, and Germany express lower confidence in U.S. global leadership and democratic performance than older cohorts. Similarly, in February 2025, YouGov’s EuroTrack surveys documented sharp declines in U.S. favorability across Europe, reaching historic lows in countries such as Denmark, Germany, and France. These findings have raised concerns about the erosion of American soft power among traditional European allies.</p>
<p>Despite this growing body of research, relatively little empirical work directly examines how age is associated with Europeans’ evaluations of whether the United States is moving in the “right” or “wrong” direction. Existing studies tend to focus on overall favorability or trust in leadership rather than directional assessments of U.S. politics. This study contributes to the literature by addressing this gap, using recent Eurobarometer data to assess whether age-based differences are systematically associated with perceptions of U.S. political direction at a critical moment in transatlantic relations.</p>
</section>
<section id="data-and-descriptive-statistics" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="data-and-descriptive-statistics"><span class="header-section-number">5</span> Data and Descriptive Statistics</h2>
<p>The data used in this analysis come from the Standard Eurobarometer 103, conducted in Spring 2025 and archived by the GESIS Data Archive. The Eurobarometer surveys are long-running public opinion studies that the European Commission produces and carries out through face-to-face interviews across all EU member states. These surveys aim to track the evolution of public attitudes on a wide array of social and political issues, including views on institutions, democracy, international relations, and global affairs.</p>
<p>The 2025 wave (EB 103) is valuable for this project as it was fielded during a moment of heightened geopolitical activity, including renewed conflict in the Middle East and intensified debates within the transatlantic alliance over military aid and democratic values. This timing provides a unique window into public sentiment across Europe as it responds to U.S. foreign policy actions. The dataset consists of interviews with 36,854 individuals aged 15 and above across all 27 EU member states. Of these, 25,264 respondents provided valid, complete answers to all variables of interest in this analysis and are included in the cleaned analytical sample.</p>
<p>Eurobarometer data are widely used in political science and sociology due to their methodological consistency, national representativeness, and inclusion of both attitudinal and demographic measures. While the survey is cross-sectional and self-reported, it remains one of the most authoritative sources of comparative public opinion data in Europe.</p>
<section id="key-variables" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="key-variables"><span class="header-section-number">5.1</span> Key Variables</h3>
<p>The dependent variable in this study is <em>perception of U.S. political direction</em>, operationalized through a survey item asking respondents whether they believe “things in the United States are going in the right direction or wrong direction.” This variable has been recoded into a binary measure (USPositive), where 1 indicates a response of “Right direction” and 0 corresponds to “Wrong direction.” Responses such as “Don’t Know” or “Refused” were excluded from the analytical sample.</p>
<p>The primary independent variable is Age, measured as a continuous variable in years (AgeNumeric). This allows for precise estimation of the relationship between respondent age and perceptions of U.S. political direction.</p>
<p>The model also includes three control variables:</p>
<ul>
<li><p>Political Ideology (IdeologyNumeric): Measured via a self-placement on a 1–10 left–right political spectrum, with 1 indicating the far left and 10 indicating the far right. Respondents who selected “Don’t know” or refused to answer (values 97 and 98) were excluded from the analysis.</p></li>
<li><p>Social Class (SocialClass): A self-assessed five-point ordinal scale where respondents classify themselves from working class to upper class. Although subjective, this variable provides an important proxy for socio-economic background.</p></li>
<li><p>The Gender variable includes four categories: male (1), female (2), non-binary or “none of the above” (3), and “prefer not to say” (4). All responses are retained in the analysis.</p></li>
</ul>
<p>After cleaning and filtering, the final dataset includes 25,264 observations across the five key variables. This cleaned dataset forms the basis for all descriptive statistics, visualizations, and regression analysis reported below.</p>
</section>
<section id="summary-statistics" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="summary-statistics"><span class="header-section-number">5.2</span> Summary Statistics</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">echo =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">fig.align =</span> <span class="st">"center"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">fig.width =</span> <span class="dv">7</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">fig.height =</span> <span class="fl">4.5</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">out.width =</span> <span class="st">"100%"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">tidy =</span> <span class="cn">TRUE</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.2
✔ ggplot2   4.0.0     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjlabelled)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'sjlabelled'

The following object is masked from 'package:forcats':

    as_factor

The following object is masked from 'package:dplyr':

    as_label

The following object is masked from 'package:ggplot2':

    as_label</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggdag)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'ggdag'

The following object is masked from 'package:stats':

    filter</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'haven'

The following objects are masked from 'package:sjlabelled':

    as_factor, read_sas, read_spss, read_stata, write_sas, zap_labels</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>jbeta_palette <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"navy"</span>       <span class="ot">=</span> <span class="st">"#1F3556"</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"light_aqua"</span> <span class="ot">=</span> <span class="st">"#BEE7E7"</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"blue"</span>       <span class="ot">=</span> <span class="st">"#4FA3D1"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"teal"</span>       <span class="ot">=</span> <span class="st">"#149B9B"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"forest"</span>     <span class="ot">=</span> <span class="st">"#053206"</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Preparing data</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>SAVdata <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">"/Users/joshua/Desktop/Documents/Documents/Education/DACSS/DACSS 603/Final Project/Datasets/St. Eurobarometer 103, Spr. 25, Vol A/ZA8843_v1-0-0.sav"</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(SAVdata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 36587   564</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Facilitates rendering</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">modelsummary_factory_default =</span> <span class="st">"kableExtra"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">modelsummary_output =</span> <span class="st">"kableExtra"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Creates the data frame</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>CompleteDataframe <span class="ot">&lt;-</span> SAVdata <span class="sc">%&gt;%</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">USdirection =</span> d73_3,      </span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">AgeExact    =</span> d11,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">IdeologyRaw =</span> d1,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">SocialClass =</span> d63,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">Gender      =</span> d10,</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">Weight      =</span> w1</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">USPositive =</span> <span class="fu">case_when</span>(</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>      USdirection <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>      USdirection <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">IdeologyNumeric =</span> readr<span class="sc">::</span><span class="fu">parse_number</span>(<span class="fu">as.character</span>(IdeologyRaw)),</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">AgeNumeric  =</span> <span class="fu">as.numeric</span>(AgeExact)</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>IdeologyNumeric <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">97</span>, <span class="dv">98</span>)) <span class="sc">%&gt;%</span>  <span class="co"># &lt;-- Exclude 'Don't Know' (97 value) and 'Refusal' (98 value)</span></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(USPositive, IdeologyNumeric, AgeNumeric)</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(CompleteDataframe)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 25264     9</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(CompleteDataframe)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["USdirection"],"name":[1],"type":["dbl+lbl"],"align":["right"]},{"label":["AgeExact"],"name":[2],"type":["dbl+lbl"],"align":["right"]},{"label":["IdeologyRaw"],"name":[3],"type":["dbl+lbl"],"align":["right"]},{"label":["SocialClass"],"name":[4],"type":["dbl+lbl"],"align":["right"]},{"label":["Gender"],"name":[5],"type":["dbl+lbl"],"align":["right"]},{"label":["Weight"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["USPositive"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["IdeologyNumeric"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["AgeNumeric"],"name":[9],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"27","3":"5","4":"2","5":"2","6":"2.0325896","7":"0","8":"5","9":"27"},{"1":"2","2":"63","3":"4","4":"3","5":"2","6":"0.6681240","7":"0","8":"4","9":"63"},{"1":"2","2":"47","3":"6","4":"3","5":"2","6":"1.0869687","7":"0","8":"6","9":"47"},{"1":"2","2":"56","3":"2","4":"3","5":"1","6":"0.7700505","7":"0","8":"2","9":"56"},{"1":"2","2":"71","3":"7","4":"2","5":"2","6":"0.4927410","7":"0","8":"7","9":"71"},{"1":"2","2":"60","3":"6","4":"1","5":"2","6":"0.6681240","7":"0","8":"6","9":"60"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Uncovering the actual count of responses for each </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>df_counts <span class="ot">&lt;-</span> CompleteDataframe <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(USPositive) <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Response =</span> <span class="fu">ifelse</span>(USPositive <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Right Direction"</span>, <span class="st">"Wrong Direction"</span>),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Percent =</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> n <span class="sc">/</span> <span class="fu">sum</span>(n), <span class="dv">1</span>),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Label =</span> <span class="fu">paste0</span>(n, <span class="st">" ("</span>, Percent, <span class="st">"%)"</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphing responses</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_counts, <span class="fu">aes</span>(<span class="at">x =</span> Response, <span class="at">y =</span> n, <span class="at">fill =</span> Response)) <span class="sc">+</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Label), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Figure 1. Respondent Opinions on U.S. Political Direction"</span>,</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Perception of U.S. Direction"</span>,</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of Respondents"</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="fu">max</span>(df_counts<span class="sc">$</span>n) <span class="sc">*</span> <span class="fl">1.15</span>) <span class="sc">+</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Right Direction"</span> <span class="ot">=</span> <span class="st">"#149B9B"</span>,</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Wrong Direction"</span> <span class="ot">=</span> <span class="st">"#1F3556"</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Website-Ed.-The-Generational-Divide_files/figure-html/-%20Loading%20Packages,%20Preparing%20Data,%20and%20Presenting%20Initial%20Findings-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Developing summary statistics</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(CompleteDataframe <span class="sc">%&gt;%</span> <span class="fu">select</span>(USPositive, AgeNumeric, IdeologyNumeric))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   USPositive       AgeNumeric    IdeologyNumeric 
 Min.   :0.0000   Min.   :15.00   Min.   : 1.000  
 1st Qu.:0.0000   1st Qu.:35.00   1st Qu.: 4.000  
 Median :0.0000   Median :51.00   Median : 5.000  
 Mean   :0.3694   Mean   :50.14   Mean   : 5.424  
 3rd Qu.:1.0000   3rd Qu.:65.00   3rd Qu.: 7.000  
 Max.   :1.0000   Max.   :99.00   Max.   :10.000  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>CompleteDataframe <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(USPositive, AgeNumeric, IdeologyNumeric) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>() <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Summary Statistics of Variables"</span>) <span class="co">#wrapping the summary so that it renders as a table</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary Statistics of Variables</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">USPositive</th>
<th style="text-align: left;">AgeNumeric</th>
<th style="text-align: left;">IdeologyNumeric</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Min. :0.0000</td>
<td style="text-align: left;">Min. :15.00</td>
<td style="text-align: left;">Min. : 1.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">1st Qu.:0.0000</td>
<td style="text-align: left;">1st Qu.:35.00</td>
<td style="text-align: left;">1st Qu.: 4.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Median :0.0000</td>
<td style="text-align: left;">Median :51.00</td>
<td style="text-align: left;">Median : 5.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Mean :0.3694</td>
<td style="text-align: left;">Mean :50.14</td>
<td style="text-align: left;">Mean : 5.424</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">3rd Qu.:1.0000</td>
<td style="text-align: left;">3rd Qu.:65.00</td>
<td style="text-align: left;">3rd Qu.: 7.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Max. :1.0000</td>
<td style="text-align: left;">Max. :99.00</td>
<td style="text-align: left;">Max. :10.000</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="model-fitting-and-hypothesis-testing" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="model-fitting-and-hypothesis-testing"><span class="header-section-number">6</span> Model Fitting and Hypothesis Testing</h2>
<p>To test the hypothesis, I utilize a Multiple Linear Regression model. Since the outcome variable is binary, this approach is interpreted as a Linear Probability Model (LPM). This is a standard approach in econometrics (Angrist &amp; Pischke, 2009, pp.&nbsp;45-48) that allows for direct interpretation of coefficients as percentage-point changes in probability. While the analysis is informed by a causal framework, the results are interpreted as conditional associations rather than causal effects due to the cross-sectional nature of the data. Specifically, after holding political ideology, gender, and social class constant (condition), age is statistically associated with differences in perceptions of U.S. political direction.</p>
<section id="causal-assumptions-dag" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="causal-assumptions-dag"><span class="header-section-number">6.1</span> Causal Assumptions (DAG)</h3>
<p>Figure 2 presents a Directed Acyclic Graph (DAG) representing the hypothesized relationships among variables. Age is treated as an exogenous predictor that may shape respondents’ political ideology, social class, and perceptions of the United States. Gender is also modeled as affecting both ideology and class, given existing research on gender-based differences in political orientation and socioeconomic positioning. Furthermore, social class is positioned in the DAG to influence political ideology, reflecting the idea that economic status and occupational identity can shape political beliefs. All four predictors (age, ideology, class, and gender) are assumed to directly influence respondents’ evaluations of whether the United States is moving in the “right” direction. However, it is this reason why in order to estimate the association between age and U.S. perceptions, I must control for ideology, class, and gender because they are plausibly related to both age and the outcome. This framework helps clarify confounding structures and supports the inclusion of appropriate control variables in the regression analysis.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>dag_coords <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">name =</span> <span class="fu">c</span>(<span class="st">"Age"</span>, <span class="st">"US_View"</span>, <span class="st">"Ideology"</span>, <span class="st">"Class"</span>, <span class="st">"Gender"</span>),</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">1</span>),</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">2</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>my_dag <span class="ot">&lt;-</span> <span class="fu">dagify</span>(</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  US_View <span class="sc">~</span> Age <span class="sc">+</span> Ideology <span class="sc">+</span> Class <span class="sc">+</span> Gender,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  Ideology <span class="sc">~</span> Age <span class="sc">+</span> Gender <span class="sc">+</span> Class,  <span class="co"># &lt;-- Class added here</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  Class <span class="sc">~</span> Age <span class="sc">+</span> Gender,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">coords =</span> dag_coords</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggdag</span>(my_dag, <span class="at">text =</span> <span class="cn">FALSE</span>, <span class="at">use_labels =</span> <span class="st">"name"</span>) <span class="sc">+</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Figure 2. Directed Acyclic Graph Mapping Dependencies"</span>) <span class="sc">+</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_dag</span>() <span class="sc">+</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Website-Ed.-The-Generational-Divide_files/figure-html/-%20Creating%20a%20DAG-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="regression-results" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="regression-results"><span class="header-section-number">6.2</span> Regression Results</h3>
<p>I fit the following model:</p>
<p><span class="math display">\[
Y_i = \beta_0
+ \beta_1 \,\text{Age}_i
+ \beta_2 \,\text{Ideology}_i
+ \beta_3 \,\text{Class}_i
+ \beta_4 \,\text{Gender}_i
+ \epsilon_i
\]</span></p>
<p>Table 2 presents the results. The coefficient for Age is statistically significant (<span class="math inline">\(p &lt; 0.001\)</span>).</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(USPositive <span class="sc">~</span> AgeNumeric <span class="sc">+</span> IdeologyNumeric <span class="sc">+</span> Gender <span class="sc">+</span> SocialClass, <span class="at">data =</span> CompleteDataframe)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = USPositive ~ AgeNumeric + IdeologyNumeric + Gender + 
    SocialClass, data = CompleteDataframe)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.5773 -0.3819 -0.2940  0.5759  0.8670 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      0.4717961  0.0166342  28.363   &lt;2e-16 ***
AgeNumeric      -0.0036574  0.0001650 -22.169   &lt;2e-16 ***
IdeologyNumeric  0.0170917  0.0013539  12.624   &lt;2e-16 ***
Gender          -0.0088500  0.0059739  -1.481    0.139    
SocialClass      0.0006552  0.0027978   0.234    0.815    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4766 on 25259 degrees of freedom
Multiple R-squared:  0.02507,   Adjusted R-squared:  0.02492 
F-statistic: 162.4 on 4 and 25259 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       2.5 %       97.5 %
(Intercept)      0.439192099  0.504400090
AgeNumeric      -0.003980778 -0.003334031
IdeologyNumeric  0.014437945  0.019745545
Gender          -0.020559219  0.002859208
SocialClass     -0.004828600  0.006139020</code></pre>
</div>
</div>
</section>
<section id="confidence-intervals-and-uncertainty" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="confidence-intervals-and-uncertainty"><span class="header-section-number">6.3</span> Confidence Intervals and Uncertainty</h3>
<p>To assess the precision of the estimated relationships, 95% confidence intervals were calculated for each regression coefficient. These intervals provide a range of plausible values for the true population effects and offer insight beyond point estimates and p-values.</p>
<p>The confidence interval for Age ranges from −0.00398 to −0.00333, excluding zero. This narrow interval indicates a precisely estimated and consistently negative relationship between age and positive perceptions of U.S. political direction. Substantively, this suggests that older Europeans are systematically less likely to view the United States as moving in the right direction, even when accounting for political ideology, gender, and social class. The tight bounds of the interval reinforce confidence in the direction and magnitude of this association.</p>
<p>Political ideology also exhibits a statistically meaningful relationship. The 95% confidence interval for Ideology spans 0.014 to 0.020, indicating that movement toward the political right is associated with an increased probability of viewing the U.S. favorably. Like age, the interval does not include zero, suggesting a substantively meaningful association.</p>
<p>In contrast, the confidence intervals for Gender (−0.021 to 0.003) and Social Class (−0.005 to 0.006) both include zero, indicating that these effects are not distinguishable from zero at conventional confidence levels. This implies greater uncertainty around the role of gender and class in shaping perceptions of U.S. political direction within this model.</p>
<p>Overall, the confidence intervals reinforce the central finding of the analysis: age and political ideology are the primary correlates of Europeans’ evaluations of U.S. political direction, while other demographic factors play a more limited role. Importantly, the direction of the age effect contradicts the original hypothesis, highlighting a generational pattern that runs counter to expectations derived from traditional soft power theories.</p>
</section>
<section id="exploring-the-interaction-between-age-and-political-ideology" class="level3" data-number="6.4">
<h3 data-number="6.4" class="anchored" data-anchor-id="exploring-the-interaction-between-age-and-political-ideology"><span class="header-section-number">6.4</span> Exploring the Interaction Between Age and Political Ideology</h3>
<p>To briefly explore whether the effect of age on U.S. favorability varies by political ideology, the figure below entitled, “Figure 1. U.S. Favorability by Age and Political Ideology”, plots the probability of viewing the United States positively across the age spectrum, separated by self-reported ideological position (on a scale from 1 = Left to 10 = Right). Several important patterns emerge.</p>
<p>First, across almost all ideological groups, favorability toward the U.S. declines with age, confirming that younger Europeans tend to view the U.S. more positively regardless of ideology, contrary to the hypothesis. Second, the gap between ideological groups is clearly visible. Respondents on the political right are consistently more favorable toward the U.S. than those on the left, particularly at younger ages. Finally, among older respondents (age 60+), differences by ideology converge a bit, suggesting that political ideology is a stronger predictor of U.S. favorability among younger Europeans.</p>
<p>This interaction highlights the complexity of transatlantic attitudes, suggesting that age and ideology posess independent and intersecting influences on how the U.S. is perceived.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CompleteDataframe, <span class="fu">aes</span>(<span class="at">x =</span> AgeNumeric, <span class="at">y =</span> USPositive, <span class="at">color =</span> <span class="fu">as.factor</span>(IdeologyNumeric))) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Figure 2. U.S. Favorability by Age and Political Ideology"</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age"</span>, <span class="at">y =</span> <span class="st">"Probability of Positive View"</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Ideology (1=Left, 10=Right)"</span>) <span class="sc">+</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Website-Ed.-The-Generational-Divide_files/figure-html/-%20Interacting%20Ideology%20and%20Age-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>To further complement the numerical summary, the figure below entitled, “Figure 3. Share of Europeans Viewing the U.S. Positively by Age Group”, shows the proportion of respondents who view the United States as moving in the right direction, broken down by age group. A clear downward trend is visible that indicates younger Europeans are significantly less likely to express a favorable opinion of the U.S. political trajectory than older cohorts.</p>
<p>This pattern offers preliminary visual evidence consistent with the hypothesis and suggests that age may play a meaningful role in shaping transatlantic attitudes. However, inconsistent with the hypothesis, the observed relationship runs in the opposite direction than expected, with younger respondents appearing more likely to view the United States as moving in the right direction.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>CompleteDataframe <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">AgeGroup =</span> <span class="fu">cut</span>(AgeNumeric,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">18</span>, <span class="dv">29</span>, <span class="dv">44</span>, <span class="dv">59</span>, <span class="cn">Inf</span>),</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"18–29"</span>, <span class="st">"30–44"</span>, <span class="st">"45–59"</span>, <span class="st">"60+"</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(AgeGroup)) <span class="sc">%&gt;%</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(AgeGroup) <span class="sc">%&gt;%</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">PositiveShare =</span> <span class="fu">mean</span>(USPositive)) <span class="sc">%&gt;%</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> AgeGroup, <span class="at">y =</span> PositiveShare)) <span class="sc">+</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"#4FA3D1"</span>) <span class="sc">+</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Figure 3. Share of Europeans Viewing the U.S. Positively by Age Group"</span>,</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age Group"</span>,</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion Positive"</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Website-Ed.-The-Generational-Divide_files/figure-html/-%20Visualizing%20Age-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation" class="level3" data-number="6.5">
<h3 data-number="6.5" class="anchored" data-anchor-id="interpretation"><span class="header-section-number">6.5</span> Interpretation</h3>
<p>The regression results support the counterintuitive but statistically significant finding that younger Europeans are more likely to view the United States as moving in the right direction. The coefficient for age is −0.004 and statistically significant (p &lt; 0.001), indicating that for each additional year of age, the probability of holding a positive view of the U.S. decreases by approximately 0.4 percentage points. Substantively, this implies that, holding other factors constant, a 25-year-old is roughly 20 percentage points more likely than a 75-year-old to view the U.S. favorably. This represents a large and meaningful effect in the context of public opinion research.</p>
<p>Political ideology is also a statistically significant predictor of U.S. favorability. Moving one point to the right on the ideological scale is associated with an increase of approximately 1.7 percentage points in the probability of viewing the U.S. positively, indicating a moderate but substantively meaningful effect. Gender and social class, by contrast, are not statistically significant predictors in this model, suggesting that age and ideology account for most of the systematic variation captured by the included covariates.</p>
<p>Taken together, these findings indicate that age is the strongest predictor in the model and that, contrary to expectations rooted in soft power theory, younger cohorts currently hold more favorable views of the United States than older Europeans.</p>
</section>
</section>
<section id="diagnostics-and-model-evaluation" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="diagnostics-and-model-evaluation"><span class="header-section-number">7</span> Diagnostics and Model Evaluation</h2>
<p>To ensure the validity of the Linear Probability Model, I examined standard regression diagnostics.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Website-Ed.-The-Generational-Divide_files/figure-html/-%20Regression%20Diagnostics-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li><p><strong>Residuals vs Fitted:</strong> The two distinct horizontal bands correspond to the binary outcome variable (USPositive), which takes on only 0 or 1 values. The red line is relatively flat, suggesting that the linear approximation is reasonable for most fitted values. However, because this is a Linear Probability Model, this diagnostic has limited value beyond detecting gross nonlinearity.</p></li>
<li><p><strong>Normal Q-Q:</strong> The Q-Q plot shows some deviation from normality at the tails, which is expected in LPMs. However, the Central Limit Theorem justifies inference about coefficients in large samples (<span class="math inline">\(N &gt; 25{,}000\)</span>), so statistical testing remains valid despite mild violations of normality.</p></li>
<li><p><strong>Scale-Location:</strong> There is some heteroscedasticity in the residuals, which is expected in binary models. This reflects the fact that variance is a function of the mean in binary outcomes.</p></li>
<li><p><strong>Residuals vs Leverage:</strong> The plot does not reveal any influential outliers beyond Cook’s distance threshold. This suggests that no single observation is unduly affecting the regression estimates.</p></li>
</ol>
<p><strong>Model Fit:</strong> The R-squared value is modest (0.021), which is typical for social science survey data, where individual opinions are driven by unobserved factors (personal psychology, specific news consumption) not captured in demographic variables. However, the systematic relationship between Age and US Perception is statistically significant.</p>
</section>
<section id="discussion" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="discussion"><span class="header-section-number">8</span> Discussion</h2>
<p>The findings from this analysis indicate a clear and statistically significant association between age and European perceptions of U.S. political direction. Though, contrary to the original hypothesis, younger Europeans are more likely than older respondents to believe that the United States is moving in the “right direction.” This pattern holds even after controlling for political ideology, social class, and gender, suggesting that age captures an independent and meaningful dimension of transatlantic public opinion.</p>
<p>These results challenge the conclusions made in recent surveys that younger generations in Europe are increasingly disillusioned with the United States due to perceived democratic backsliding, foreign policy decisions, or value divergence. Instead, the findings suggest that older Europeans may be more skeptical of the current trajectory of the United States, potentially reflecting longer historical memory, greater exposure to past periods of U.S. unilateralism, or heightened sensitivity to recent geopolitical developments. Younger respondents, by contrast, may evaluate the United States through a different lens, one that is shaped by contemporary cultural, technological, or security-related considerations.</p>
<p>Political ideology remains an important predictor of U.S. favorability, with respondents identifying further to the political right expressing more positive views overall. However, the persistence of the age effect across ideological positions indicates that generational differences cannot be explained solely by partisan orientation. Taken together, these results suggest that age-based patterns in European attitudes toward the United States are more complex than anticipated and may not align neatly with dominant narratives about generational disaffection.</p>
<p>Overall, this study highlights the importance of empirically testing widely held assumptions about public opinion. While existing scholarship often emphasizes a decline in American soft power among younger audiences, the evidence presented here suggests that contemporary generational dynamics may be evolving in unexpected ways. Future research should further explore the mechanisms underlying these age-based differences, particularly through longitudinal-based analyses.</p>
</section>
<section id="limitations" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="limitations"><span class="header-section-number">9</span> Limitations</h2>
<p>First, the analysis relies on cross-sectional data, which prevents establishing causal relationships. While the results show that younger Europeans are more likely to view the U.S. as moving in the “right direction,” it is not possible to determine whether age itself drives these attitudes or whether unobserved cohort characteristics such as media environments, educational systems, or political events experienced during adolescence, explain the observed relationships. A longitudinal or repeated cross-sectional design would better isolate cohort effects from age or period effects.</p>
<p>Second, this study is merely a snapshot. The dependent variable is based on a single survey item, which may capture immediate reactions to specific geopolitical events rather than stable orientations toward the United States. Public opinion is sensitive to short-term shocks such as election outcomes, foreign policy crises, or media narratives, and Eurobarometer 101.3 was fielded shortly after a major political development, the return to office of President Donald Trump, which many would argue is a significant development. As a result, the “right direction” measure may reflect timing-specific sentiment rather than long-term generational attitudes.</p>
<p>Third, the study employs a Linear Probability Model (LPM). While LPMs are commonly used for their interpretability, they impose linearity on a binary outcome (i.e.&nbsp;the effect is the same across all ages) and are prone to heteroscedasticity. Although diagnostic checks suggest the model performs adequately, logistic regression could serve as a robustness check and allow for nonlinear effects or interaction terms (e.g., age × ideology) that may be masked by the LPM specification.</p>
<p>Fourth, several potentially important covariates are unavailable in the dataset. Eurobarometer does not measure media consumption, institutional trust, political sophistication, or exposure to international news, all of which may influence attitudes toward the United States. Without such controls, the model risks omitted variable bias. For example, digital media exposure may vary systematically by age and shape views of U.S. politics in ways not captured by the current predictors.</p>
<p>Finally, the pooled analysis does not account for meaningful variation between countries. Although national sampling weights are applied, the data do not permit multilevel modeling or country-level predictors. Prior studies (e.g., YouGov, Pew) suggest that favorability toward the U.S. varies sharply across Europe. A multilevel model that accounts for country-level factors such as NATO membership, bilateral relations, or governing party ideology, would offer a more complete picture of transatlantic public opinion.</p>
<p>Despite these limitations, the findings remain substantively meaningful. The use of timely, large-scale survey data reveals a generational trend that runs counter to traditional theories of U.S. soft power, where youth are assumed to be the most pro-American. In this case, older Europeans express more skepticism, offering a new and perhaps underexamined perspective on transatlantic political perception.</p>
</section>
<section id="conclusion" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">10</span> Conclusion</h2>
<p>This paper set out to determine if younger Europeans maintain a “soft power” affinity for the United States. Analyzing Eurobarometer 2025 data, I find strong evidence to the contrary. Age is a significant predictor of U.S. perceptions, with younger Europeans, not older generations, more likely to view the U.S. political direction favorably.</p>
</section>
<section id="references" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="references"><span class="header-section-number">11</span> References</h2>
<p>Angrist, J. D., &amp; Pischke, J.-S. (2009). <em>Mostly Harmless Econometrics: An Empiricist’s Companion</em>. Princeton University Press.</p>
<p>Britton, H. (2025, February). <em>European favourability of the USA falls following the return of Donald Trump</em>. YouGov. <a href="https://yougov.co.uk" class="uri">https://yougov.co.uk</a></p>
<p>Clancy, L. (2023, March 22). <em>Young adults in Europe are critical of the U.S. and China – but for different reasons</em>. Pew Research Center. <a href="https://www.pewresearch.org" class="uri">https://www.pewresearch.org</a></p>
<p>European Commission. (2025). <em>Eurobarometer 101.3: Public opinion in the European Union (Spring 2025)</em> [Data set]. GESIS Data Archive. <a href="https://doi.org/10.4232/1.14376" class="uri">https://doi.org/10.4232/1.14376</a></p>
<p>Henley, J. (2025, June 3). <em>Public support for Israel in western Europe at lowest ever recorded by YouGov</em>. The Guardian. <a href="https://www.theguardian.com" class="uri">https://www.theguardian.com</a></p>
<p>Jennings, M. K., Stoker, L., &amp; Bowers, J. (2009). Politics across generations: Family transmission reexamined. <em>The Journal of Politics, 71</em>(3), 782–799. https://doi.org/10.1017/S0022381609090719</p>
<p>Nye, J. S., Jr.&nbsp;(1990). Soft power. <em>Foreign Policy</em>, (80), 153–171. <a href="https://doi.org/10.2307/1148580" class="uri">https://doi.org/10.2307/1148580</a></p>
<p>The Economist. (2024, March 13). <em>Why young men and women are drifting apart: Diverging worldviews could affect politics, families and more</em>. <a href="https://www.economist.com" class="uri">https://www.economist.com</a></p>
<p>YouGov. (2025). <em>Eurotrack survey results: August 13–28, 2025</em>. https://docs.cdn.yougov.com</p>
<p>Leonard, M., &amp; Gressel, G. (2024, June). <em>Transatlantic twilight: European public opinion and the long shadow of Trump</em>. European Council on Foreign Relations. <a href="https://ecfr.eu/publication/transatlantic-twilight-european-public-opinion-and-the-long-shadow-of-trump/" class="uri">https://ecfr.eu/publication/transatlantic-twilight-european-public-opinion-and-the-long-shadow-of-trump/</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>